# Data Science Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.linspace() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Modulo <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Floor Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Broadcasting <br>
  &nbsp;&nbsp;&nbsp;&nbsp; f) Indexing and Assigning NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Numpy Subsetting <br>
  &nbsp;&nbsp;&nbsp;&nbsp; h) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing White Sox Hitting Numbers <br>

<p>Python Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [1]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1, 2, 3]
l_2 = [4, 5, 6]

print(l_1 + l_2)


[1, 2, 3, 4, 5, 6]


<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

In [3]:
def sum_lists(l1, l2):
    output = []
    for idx in range(len(l1)):
        output.append(l1[idx] + l2[idx])
    return output
sum_lists([2, 3, 4], [5, 12, 4])

[7, 15, 8]

In [5]:
sum_lists(l_1, l_2)

[5, 7, 9]

In [6]:
x = [[1, 2, 3], [4, 5, 6]]
y = [[10, 20, 30], [14, 15, 16]]

sum_lists(x, y)

[[1, 2, 3, 10, 20, 30], [4, 5, 6, 14, 15, 16]]

## Numpy <br>

<p>NumPy is the fundamental package for scientific computing in Python. It is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. </p>
<a href="https://numpy.org/doc/stable/index.html" target="_blank" rel="noopener">Numpy Documentation</a>


#### Importing

In [10]:
# always import as np, standard across all of data science
!pip install numpy
import numpy as np

In [11]:
np

<module 'numpy' from '/Users/kp/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>

<p>NumPy allows us to create arrays and manipulate numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be the same. NumPy arrays are faster and more compact than Python lists. A NumPy array consumes less memory and uses much less memory to store data.</p>

#### Creating an NDArray
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [12]:
# np.array([list])
arr1 = np.array([1, 2, 3])
print(arr1)
print(type(arr1))
arr1

[1 2 3]
<class 'numpy.ndarray'>


array([1, 2, 3])

In [13]:
arr2 = np.array([4, 5, 6])
arr2


array([4, 5, 6])

In [14]:
arr1+arr2

array([5, 7, 9])

In [15]:
arr3 = np.array([7, 8, '9'])
arr3

array(['7', '8', '9'], dtype='<U21')

In [16]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

###### - np.zeros()

In [ ]:
# np.zeros(shape)
# shape = the shape of the ndarray - int or tuple(RxC)


In [17]:
arr_zeros1 = np.zeros(5)
arr_zeros1

array([0., 0., 0., 0., 0.])

In [20]:
arr_zeros2 = np.zeros((5,3))
arr_zeros2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### - np.ones()

In [21]:
# np.ones(shape)
arr_ones1 = np.ones(5)
arr_ones1

array([1., 1., 1., 1., 1.])

In [24]:
arr_ones2 = np.ones((5,2))
arr_ones2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

###### - np.arange()

In [26]:
# np.arange(stop)
# np.arange(start, stop)
# np.arange(start, stop, step)
arr_range1 = np.arange(15)
arr_range1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
arr_range2 = np.arange(10,20)
arr_range2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
arr_range3 = np.arange(10,20,2)
arr_range3

array([10, 12, 14, 16, 18])

###### - np.linspace()

In [33]:
# np.linspace(start, stop, interval)
arr_lin = np.linspace(0,10, 9)
arr_lin

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

#### Performing Calculations on NDArrays

###### - Summation

In [34]:
arr_list1 = np.array([5,10,15,20,25])
arr_list2 = np.array([10,20,30,40,50])

result_sum = arr_list1 + arr_list2
result_sum

array([15, 30, 45, 60, 75])

###### - Difference

In [36]:
result_diff = arr_list1 - arr_list2
result_diff

array([ -5, -10, -15, -20, -25])

###### - Multiplication

In [37]:
result_mul = arr_list1 * arr_list2
result_mul

array([  50,  200,  450,  800, 1250])

###### - Division

In [40]:
result_div = arr_list2 / arr_list1
result_div

array([2., 2., 2., 2., 2.])

#### Modulo

In [44]:
result_mod = arr_list2 % arr_list1
result_mod

array([0, 0, 0, 0, 0])

#### Floor Division

In [43]:
result_floor = arr_list2 // arr_list1
result_floor

array([2, 2, 2, 2, 2])

#### Broadcasting

In [45]:
arr_list1

array([ 5, 10, 15, 20, 25])

In [46]:
arr_list1 * 5

array([ 25,  50,  75, 100, 125])

In [47]:
arr_list1 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

#### Concatenate

In [48]:
# np.concatenate((nda1, nda2))
arr_list3 = np.concatenate((arr_list1, arr_list2))
arr_list3

array([ 5, 10, 15, 20, 25, 10, 20, 30, 40, 50])

#### Indexing Numpy Arrays

In [ ]:
arr_idx = np.arange(10)
arr_idx

<p>But what happens when we have a multidimensional array?</p>

Similar to lists within lists. It, however, looks more like the C-programming syntax...

In [ ]:
# arr_name[row_index, col_index]


#### Assigning Values

In [ ]:
# arr_name[idx] = val OR arr_name[row_idx,col_idx] = val


#### Numpy Subsetting

##### Multiple Filters

In [ ]:
# arr_name[(first_condition) & OR | (second_condition)]


#### Checking NDArray Type

In [ ]:
# usind the .dtype() method


#### Altering NDArray Type

#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [ ]:
 # shape is always rows x columns
# Checking the Shape of the nd_m Numpy Array
# Using the method .shape


#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [ ]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column



In [ ]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)


#### In-Class Exercise #1 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrix of strings

In [ ]:
# array([['0', '1', '2', '3'],
#        ['4', '5', '6', '7'],
#        ['8', '9', '10', '11'],
#        ['12', '13', '14', '15']], dtype='<U11')



#### Complex Indexing & Assinging

#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [ ]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

In [ ]:
# np.random.randint()

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.randint(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.randint(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.randint(0, 10, (3, 3)))

## Working With CSV's

#### Imports

In [ ]:
import csv
from datetime import datetime

In [ ]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]


In [ ]:
# Hitters who had more than 100 hits


In [ ]:
# Hitters who had less than 10 home runs


In [ ]:
# find total rbis


# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>